language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - yarn build

deploy:
  provider: surge
  skip_cleanup: true
  domain: https://danielpiva.surge.sh
  project: ./dist/
  on:
    branch: master
  provider: surge
  skip_cleanup: true
  domain: https://imdanielpiva.surge.sh
  project: ./dist/
  on:
    all_branches: true
